
name: Node CI

on:
  - push
  - pull_request
    
env:
  CI: true
  CC_TEST_REPORTER_ID: ${{ secrets.REPORTERID }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: paambaati/codeclimate-action@v2.2.4
      
    - name: Install dependencies
      run: make install
      
    - name: Run lint
      run: make lint
      
    - name: Test coverage
      run: make test-coverage

#     - name: Test & publish code coverage
#       # Publish code coverage on Code Climate
#       # https://github.com/paambaati/codeclimate-action
#       uses: paambaati/codeclimate-action@v3
#       # Add Code Climate secret key
#       env:
#         CC_TEST_REPORTER_ID: ${{ secrets.REPORTERID }}
#       with:
#         coverageCommand: make test-coverage
#         debug: true
