
name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make install
      
    - name: Run lint
      run: make lint
      
    - name: Run test
      run: make test
